name: astroneudl
channels:
  - defaults
dependencies:
  - python=3.7.16
  - h5py=2.9.0
  - hdf5=1.10.4
  - imageio=2.6.1
  - keras=2.2.4
  - matplotlib=3.1.1
  - numpy=1.16.4
  - scikit-image=0.15.0
  - scikit-learn=0.21.3
  - scipy=1.3.0
  - tensorflow=1.15.2
  - tensorflow-gpu=1.15.2 
  - pandas=1.0.3
  - imglyb=2.0.1
  - ipywidgets=7.7.0
  - itkwidgets=0.32.0
  - jgo=1.0.3
  - jpype1=1.3.0
  - jupyter_contrib_nbextensions=0.5.1
  - napari=0.4.15
  - notebook=6.4.11
  - numpy=1.22.3
  - openjdk=8.0.312
  - pyimagej=1.2.1
  - scikit-image=0.19.2
  - scipy=1.8.0
  - scyjava=1.5.1
  - xarray=2022.3.0
