name: astroneudl
channels:
  - defaults
dependencies:
  - cudatoolkit: 10.1.243 
  - cudnn: 7.6.5 
  - h5py: 2.9.0
  - hdf5: 1.10.4
  - imageio: 2.6.1
  - keras: 2.2.4
  - matplotlib: 3.1.1
  - numpy: 1.16.4
  - python: 3.6.7
  - scikit-image: 0.15.0
  - scikit-learn: 0.21.3
  - scipy: 1.3.0
  - tensorflow: 1.15.2
  - tensorflow-gpu: 1.15.2 
  - pandas: 1.0.3